### ISSUE TITLE
DQN not running

### ISSUE THREAD

**Issue by JaxDraxler** [erlerobot/gym-gazebo#133] opened 2018-04-16 15:42 UTC
Hello !!
I've setup the bridge and the circuit2_turtlebot_lidar_qlearn.py is working perfectly. 
However, when i try to run the dqn file i get no error but i also get no output, so the program gets stuck like its waiting for something.

![image](https://user-images.githubusercontent.com/38314657/38820171-793ac27a-419d-11e8-81ef-3f345dd3260b.png)

Any thoughts ??

**Comment by mkhansen-intel** [comment] 2018-04-16 17:12
@JaxDraxler - you are probably running into the error described here: (#122 ). This was fixed but a subsequent push to master over-wrote it so it needs to be fixed again. For now you could try that PR locally by doing this: 
```
git fetch origin pull/122/head:fix_dqn
git checkout fix_dqn
```
That will create a new local branch with the fix in it and checkout that branch. Hopefully this will help you in the short term until the issue is resolved in master branch again.

**Comment by JaxDraxler** [comment] 2018-04-17 07:59
Hello thank you for the fast response !! I tried the pull request put it didn't work. Is there a specific directory where it should have been done ?

**Comment by JaxDraxler** [comment] 2018-04-17 14:47
I'm getting an error about the monitor at first. I'll try and fix it, i think it is because the file is written in older python language not python3 maybe !!

![image](https://user-images.githubusercontent.com/38314657/38877336-cba99b78-425e-11e8-8f5f-d0a509a5d7ef.png)

**Comment by mkhansen-intel** [comment] 2018-04-17 14:55
@JaxDraxler - I fixed this in PR#130, which is now merged to master branch. You can get this change by re-pulling the master branch. If you run in to the other issue, I've submitted PR#132 to fix that, so you can pull that PR to get the latest working version. Let me know if you need more help.

**Comment by JaxDraxler** [comment] 2018-04-18 08:15
@mkhansen-intel  
Hello !! Thank you for the fix, I've also found an issue in the /gym-gazebo/examples/turtlebot/memory.py 
They were using an array at line 21 instead of a list, so the simulation would stop after two episodes.
After the fix i've got this:

![image](https://user-images.githubusercontent.com/38314657/38919626-569bc52a-42f1-11e8-9f0f-d52d162b1fd7.png)

**Comment by mkhansen-intel** [comment] 2018-04-18 22:04
@JaxDraxler  - What was the issue you found in memory.py, can you file a new issue on that and submit a PR to fix it?

**Comment by JaxDraxler** [comment] 2018-04-19 07:28
@mkhansen-intel Sure !!

**Closed** 2018-04-19 07:51 UTC
